sudo: true
language: haskell

cache:
  directories:
    - $HOME/.stack

ghc:
  - "8.0.2"
  - "8.4.4"
  - "8.6.5"

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack --no-terminal --skip-ghc-check test

notifications:
  email: false
